
- name: Create /var/src
  file: path=/var/src state=directory mode=0755
  become: yes

- name: Copy docker-compose file to server
  copy:
    src: "{{ role_path }}/files/docker-compose-production.yml"
    dest: /var/src/docker-compose.yml
    owner: gitlab-ci
  become: yes

- name: Start up event bus dependencies via docker compose
  docker_service:
    project_src: /var/src
    state: present
    pull: yes
  register: output

- name: Ensure necessary services are running
  assert:
    that:
      - "zookeeper.src_zookeeper_1.state.running"
      - "kafka.src_kafka_1.state.running"
      - "connect.src_connect_1.state.running"
      - "couchbase.db.src_couchbase.db_1.state.running"
