
variables:
  REGISTRY: sed-team-project:4567
  REG_EVENT_BUS: sed-team-project:4567/sed-dev-group/sed-dev-project:event-bus
  REG_KAFKA_CONNECT: sed-team-project:4567/sed-dev-group/sed-dev-project:kafka-connect

  EVENT_BUS_TAG_THIS_BUILD: $REG_EVENT_BUS-$CI_PIPELINE_ID
  KAFKA_CONNECT_TAG_THIS_BUILD: $REG_KAFKA_CONNECT-CI_PIPELINE_ID

stages:
  - test
  - build
  - publish
  - deploy

compile_dissertation_latex:
  image: blang/latex
  stage: publish
  script:
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
  only:
    - master

test_event_bus:
  image: rust:1.21
  stage: test
  script:
    # - cd event-bus
    # - cargo test
    - echo "Pass"

build_event_bus:
  image: docker:latest
  stage: build
  script:
    - cd event-bus
    - docker build -t $EVENT_BUS_TAG_THIS_BUILD .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $EVENT_BUS_TAG_THIS_BUILD

build_kafka_connect:
  image: docker:latest
  stage: build
  script:
    - cd persistence/connect-custom
    - docker build -t $KAFKA_CONNECT_TAG_THIS_BUILD .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $KAFKA_CONNECT_TAG_THIS_BUILD

tag_production_images:
  image: docker:latest
  stage: publish
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY

    - docker pull $EVENT_BUS_TAG_THIS_BUILD
    - docker tag $EVENT_BUS_TAG_THIS_BUILD $REG_EVENT_BUS
    - docker push $REG_EVENT_BUS

    - docker pull $KAFKA_CONNECT_TAG_THIS_BUILD
    - docker tag $KAFKA_CONNECT_TAG_THIS_BUILD $REG_KAFKA_CONNECT
    - docker push $REG_KAFKA_CONNECT
  only:
    - ci # temp, for testing
    - master

deploy_to_sed_deploy:
  image: williamyeh/ansible:ubuntu16.04
  stage: deploy
  script:
    - cd deploy
    - ansible-galaxy install angstwad.docker_ubuntu
    - ansible-playbook -e 'host_key_checking=False' -i inventory playbook.yml --user gitlab-ci --extra-vars "ansible_ssh_pass=$DEPLOY_USER_PASSWORD ansible_become_pass=$DEPLOY_USER_PASSWORD registry_password=$CI_BUILD_TOKEN"
  only:
    - ci # temp, for testing
    - master
