
variables:
  REGISTRY: sed-team-project:4567
  REG_EVENT_BUS: $REGISTRY/sed-dev-group/sed-dev-project
  REG_KAFKA_CONNECT: $REGISTRY/sed-dev-group/sed-dev-project

stages:
  - test
  - build
  - deploy

compile_dissertation_latex:
  image: blang/latex
  stage: build
  script:
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
  only:
    - master

test_event_bus:
  image: debian:jessie
  stage: test
  script:
    - echo "Aw darn, there's no tests yet!"

build_event_bus:
  image: docker:latest
  stage: build
  script:
    - cd event-bus
    - docker build -t $REG_EVENT_BUS:event-bus-$CI_PIPELINE_ID .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $REG_EVENT_BUS:event-bus-$CI_PIPELINE_ID

build_kafka_connect:
  image: docker:latest
  stage: build
  script:
    - cd persistence/connect-custom
    - docker build -t $REG_KAFKA_CONNECT:kafka-connect-$CI_PIPELINE_ID .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $REG_KAFKA_CONNECT:kafka-connect-$CI_PIPELINE_ID

deploy_to_sed_deploy:
  image: debian:jessie
  stage: deploy
  script:
    - echo "TODO implement deploying to our server"
  only:
    - master
