version: '2.2'

networks:
  persistence:
    driver: bridge

services:
  connect:
    build: ../persistence/connect-custom/
    restart: always
    ports:
      - "8083:8083"
    networks:
      - hostnet
      - kafka-public
      - persistence
    command: connect-standalone worker.properties couchbase-sink.properties

  couchbase.db:
    image: couchbase
    networks:
      - hostnet
      - persistence
    ports:
      - 8091-8094:8091-8094
      - 11210-11211:11210-11211
    volumes:
      - ../persistence/cb/data:/opt/couchbase/var/lib/couchbase/data
