
- name: Create /var/event-bus
  file: path=/var/event-bus state=directory mode=0755
  become: yes

- name: Copy docker-compose file to server
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: /var/event-bus/docker-compose.yml
    owner: gitlab-ci
  become: yes

- name: Start up event bus dependencies via docker compose
  docker_service:
    project_src: /var/event-bus
    state: present
    pull: yes
  register: output
  become: yes

- name: Ensure necessary services are running
  assert:
    that:
      - "event-bus.event-bus_event-bus_1.state.running"
  become: yes
